<?php

namespace RashidHamidov\ModelForm;

use Illuminate\Support\ServiceProvider;

class ModelFormServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadViewsFrom(__DIR__.'/../views', 'model-form');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
